/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/cosign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate a frozen transaction body and co-sign it, or name the denied members.
         * @description Greedy in submission order: each member is judged against the state that includes every member
         *     admitted before it. A denied member consumes nothing. A signed batch is committed: the admitted
         *     amounts are consumed from every window at signing time.
         *
         *     Idempotent on `Idempotency-Key` (the `batchId`): the same key with the same `txBodyHash` replays
         *     the stored response byte for byte; the same key with a different `txBodyHash` supersedes the
         *     previous decision and releases its hold.
         */
        post: operations["cosign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a minted guarded wallet with its mandate.
         * @description A wallet is identified by the pair (`walletAddress`, `stateToken`): every guarded wallet on one
         *     validator shares its address, so a different `stateToken` at a registered address is a new wallet
         *     with its own `walletId`. Idempotent on the pair: the same body again returns 200 with the same
         *     result; a different body for an already registered pair is a 409 `wallet_exists`.
         */
        post: operations["registerWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{walletId}/read-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a short-lived read token for one wallet.
         * @description The token is opaque, scoped to this wallet's read endpoints, and expires after 15 minutes.
         */
        post: operations["mintReadToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{walletId}/mandate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The wallet's mandate, as rules and as plain English. */
        get: operations["getMandate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{walletId}/allowance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live remaining allowance per rule, and the on-chain period budget.
         * @description Never shows a number the chain disagrees with; `discrepancy` is set when the two views differ.
         */
        get: operations["getAllowance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{walletId}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paged decisions for one wallet. */
        get: operations["listDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/{decisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One decision with its request and Merkle inclusion proof. */
        get: operations["getDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{walletId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quorum status, attestation freshness, last co-sign, degraded flags. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/journal/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Published journal Merkle roots and where they are anchored.
         * @description One root per wallet per publication; `from`/`to` bound `publishedAt`.
         */
        get: operations["listRoots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallets/{walletId}/evidence.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The evidence bundle - mandate, decisions, roots, proofs, verification instructions.
         * @description A stored zip of `mandate.json`, `decisions.jsonl` (decisions in `from`/`to`, default the last
         *     30 days), `roots.jsonl`, `proofs/<decisionId>.json`, `publisher.json`, `VERIFY.md` and
         *     `README.txt`, verifiable offline with `exchain-verify`.
         */
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness. */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Minor units of the named asset, as a decimal string. Never a JSON number. */
        Amount: string;
        /** @description `lovelace`, or `<policyId 56 hex>.<assetName hex, 0..64 hex>`. Lowercase only. */
        AssetId: string;
        AssetSpec: {
            id: components["schemas"]["AssetId"];
            /**
             * @description Minor-unit decimals of the governed asset. Contract version 1.0 accepts only 6, so the
             *     engine's fixed-point scale and the asset's minor unit coincide (lovelace, USDCx and the
             *     other 6-decimal Cardano stablecoins). Registration with any other value is a 400.
             * @enum {integer}
             */
            decimals: 6;
        };
        /** @description A 28-byte Cardano key hash, hex. */
        KeyHash: string;
        /** @description A 32-byte hash, hex. */
        Hash32: string;
        Blake2b256: string;
        /** @description A Cardano payment address, `addr` (mainnet) or `addr_test` (preprod). */
        Bech32Address: string;
        /** @description A ULID (uppercase Crockford base32) with the `dec_` prefix. */
        DecisionId: string;
        /** @description A ULID (uppercase Crockford base32) with the `wal_` prefix. */
        WalletId: string;
        /** Format: uuid */
        Uuid: string;
        /**
         * Format: date-time
         * @description RFC 3339, UTC.
         */
        DateTime: string;
        /**
         * @description Why a member or a batch was denied. Fourteen wire strings across the twelve rows of
         *     `MASUMI_INTEGRATION.md` §3.4 (`hourly_outflow`, `daily_outflow` and `monthly_outflow` share one
         *     row) plus the three Masumi rules of contract 1.1: `per_agent_cap`, `price_above_published` and
         *     `counterparty_blocked`. `member_denied` is an envelope marker meaning "see `members[]`", not a
         *     code, and never appears in a member's `denied`.
         *
         *     | code | level | retryable | alarm |
         *     |---|---|---|---|
         *     | per_tx_cap | member | no | no |
         *     | hourly_outflow | member | at windowResetsAt | no |
         *     | daily_outflow | member | at windowResetsAt | no |
         *     | monthly_outflow | member | at windowResetsAt | no |
         *     | per_seller_cap | member | at windowResetsAt, or now with another counterparty | no |
         *     | velocity_burst | member | after retryAfterSec | no |
         *     | registry_gate | member | no | no |
         *     | envelope_exhausted | member | no | no |
         *     | per_agent_cap | member | at windowResetsAt | no |
         *     | price_above_published | member | no | no |
         *     | counterparty_blocked | member | no | no |
         *     | asset_not_listed | batch | no | no |
         *     | body_mismatch | batch | no | yes |
         *     | payee_unpinned | batch | no | yes |
         *     | utxo_unknown | batch | no | no |
         *     | clock_skew | batch | no | yes |
         *     | reservation_conflict | batch | immediately | no |
         * @enum {string}
         */
        DenialCode: "per_tx_cap" | "hourly_outflow" | "daily_outflow" | "monthly_outflow" | "per_seller_cap" | "velocity_burst" | "registry_gate" | "envelope_exhausted" | "per_agent_cap" | "price_above_published" | "counterparty_blocked" | "asset_not_listed" | "body_mismatch" | "payee_unpinned" | "utxo_unknown" | "clock_skew" | "reservation_conflict";
        ChainTip: {
            slot: number;
            blockHash: components["schemas"]["Hash32"];
        } | null;
        /** @description Carried by every JSON response body. */
        Envelope: {
            /**
             * Format: date-time
             * @description When the response was produced, RFC 3339 UTC with milliseconds.
             */
            asOf: string;
            /** @enum {string} */
            schemaVersion: "1.0" | "1.1";
            chainTip: components["schemas"]["ChainTip"];
        };
        Intent: {
            /** @description Unique within the batch. */
            purchaseId: string;
            /** @description The escrow output this purchase funds. Unique within the batch. */
            outputIndex: number;
            counterparty: string;
            amount: components["schemas"]["Amount"];
            asset: components["schemas"]["AssetId"];
            jobHash: components["schemas"]["Blake2b256"];
            agentIdentifier: string;
        };
        Context: {
            nodeId: string;
            orgId: string;
            submittedAt: components["schemas"]["DateTime"];
            /**
             * @deprecated
             * @description Ignored since 1.1: the wallet is resolved from the body's continuing output and from
             *     `walletUtxoRef` on the chain. Kept one release so 1.0 clients keep validating.
             */
            walletAddress?: components["schemas"]["Bech32Address"];
        };
        CosignRequestBase: {
            batchId: components["schemas"]["Uuid"];
            /**
             * @description The guarded wallet input being spent, `txHash#index`. The wallet is the one whose address and
             *     state token are together on the body's continuing output. A body with no such output resolves
             *     through this reference's address only when the node has exactly one wallet there; with several
             *     it is `utxo_unknown`, never the first match.
             */
            walletUtxoRef: string;
            /** @description In Masumi's submission order; rolling windows are consumed in this order. */
            intents: components["schemas"]["Intent"][];
            context: components["schemas"]["Context"];
        };
        CosignRequest: components["schemas"]["CosignRequestBase"] & {
            /** @description The frozen CBOR transaction body. Authoritative; `intents` is the hint it is checked against. */
            txBodyHex: string;
        };
        Bound: {
            limit: components["schemas"]["Amount"];
            used: components["schemas"]["Amount"];
            remaining: components["schemas"]["Amount"];
            windowResetsAt?: components["schemas"]["DateTime"];
            /** @description The scope group, present for scoped rules such as `per_seller_cap`. */
            scope?: string;
        };
        /** @description Rule name to its bound after this decision. */
        BoundsRemaining: {
            [key: string]: components["schemas"]["Bound"];
        };
        /**
         * @description `denied` and `reasonEnglish` are present iff `verdict` is `denied`. `bound`, `used` and
         *     `attempted` are present iff the code has a bound; `retryAfterSec` iff the code is retryable;
         *     `windowResetsAt` iff the code is a window code; `scope` iff the code is `per_seller_cap` or
         *     `per_agent_cap`.
         *     The `oneOf` branches encode exactly that: one branch per field set, keyed on `denied`, and
         *     only member-level codes appear here (batch-level codes deny at the top of `CosignDeny`).
         */
        MemberVerdict: {
            purchaseId: string;
            outputIndex: number;
            /** @enum {string} */
            verdict: "allowed" | "denied" | "not_evaluated";
            denied?: components["schemas"]["DenialCode"];
            reasonEnglish?: string;
            bound?: components["schemas"]["Amount"];
            used?: components["schemas"]["Amount"];
            attempted?: components["schemas"]["Amount"];
            retryAfterSec?: number;
            windowResetsAt?: components["schemas"]["DateTime"];
            scope?: string;
        } & ({
            purchaseId?: unknown;
            outputIndex?: unknown;
            /** @enum {string} */
            verdict?: "allowed" | "not_evaluated";
        } | {
            purchaseId?: unknown;
            outputIndex?: unknown;
            /** @enum {string} */
            verdict?: "denied";
            /** @enum {string} */
            denied: "per_tx_cap" | "envelope_exhausted" | "price_above_published";
            reasonEnglish: unknown;
            bound: unknown;
            used: unknown;
            attempted: unknown;
        } | {
            purchaseId?: unknown;
            outputIndex?: unknown;
            /** @enum {string} */
            verdict?: "denied";
            /** @enum {string} */
            denied: "hourly_outflow" | "daily_outflow" | "monthly_outflow";
            reasonEnglish: unknown;
            bound: unknown;
            used: unknown;
            attempted: unknown;
            retryAfterSec: unknown;
            windowResetsAt: unknown;
        } | {
            purchaseId?: unknown;
            outputIndex?: unknown;
            /** @enum {string} */
            verdict?: "denied";
            /** @enum {string} */
            denied: "per_seller_cap";
            reasonEnglish: unknown;
            bound: unknown;
            used: unknown;
            attempted: unknown;
            retryAfterSec: unknown;
            scope: unknown;
        } | {
            purchaseId?: unknown;
            outputIndex?: unknown;
            /** @enum {string} */
            verdict?: "denied";
            /** @enum {string} */
            denied: "velocity_burst";
            reasonEnglish: unknown;
            bound: unknown;
            used: unknown;
            attempted: unknown;
            retryAfterSec: unknown;
        } | {
            purchaseId?: unknown;
            outputIndex?: unknown;
            /** @enum {string} */
            verdict?: "denied";
            /** @enum {string} */
            denied: "per_agent_cap";
            reasonEnglish: unknown;
            bound: unknown;
            used: unknown;
            attempted: unknown;
            retryAfterSec: unknown;
            windowResetsAt: unknown;
            scope: unknown;
        } | {
            purchaseId?: unknown;
            outputIndex?: unknown;
            /** @enum {string} */
            verdict?: "denied";
            /** @enum {string} */
            denied: "registry_gate" | "counterparty_blocked";
            reasonEnglish: unknown;
        });
        Witness: {
            member: string;
            vkeyHex: string;
            signatureHex: string;
        };
        /**
         * @example {
         *       "decisionId": "dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "txBodyHash": "blake2b_256:f13f1c9731cd0d3aae2abf45e553c1fd7c94d48ba42c7515eb218aa23c247f18",
         *       "requiredSigners": [
         *         "903105119401d2618ca8b5193adfc74592a1362c07a375c3490fe90e",
         *         "b02e5e1f6167ef12fe823d259b1034f56818e92ef2b4c73722ee3412",
         *         "32c72c8379803dd1957e426ca9c11ffeb47c8dd1a644028214ef39ef",
         *         "347d7c288cd19c106e46e990bd0d38be27fe73fe7aa04b6cbdb9d4ad"
         *       ],
         *       "quorumMembers": [
         *         "exchain-eu-1a",
         *         "exchain-eu-1b"
         *       ],
         *       "witnessSetHex": "a10082825820315fee8fd468cdfbebe79a4af7ff1729e1d196f551653eeb388ca8c6c4e15baa584032a61e2a70efce2e9445873664ddc68df2478cf76945609567a7a6fbc02061ce83d57f68b1091a960b67947fe80cda9817058bd01311b0c0a40bdd61ad75ec148258204430e9941bafd1b863f8e3ffc73dc1e5943e1cc2d00efb7de15f1eab02887e315840378100766f39f15700855e4048a82590a4944abdd097d54f3ac89707e28d535bc845e030dad4a429b1b6464b9a8112f479f028c9dae467419a3e53fbc50f98eb",
         *       "witnesses": [
         *         {
         *           "member": "exchain-eu-1a",
         *           "vkeyHex": "315fee8fd468cdfbebe79a4af7ff1729e1d196f551653eeb388ca8c6c4e15baa",
         *           "signatureHex": "32a61e2a70efce2e9445873664ddc68df2478cf76945609567a7a6fbc02061ce83d57f68b1091a960b67947fe80cda9817058bd01311b0c0a40bdd61ad75ec14"
         *         },
         *         {
         *           "member": "exchain-eu-1b",
         *           "vkeyHex": "4430e9941bafd1b863f8e3ffc73dc1e5943e1cc2d00efb7de15f1eab02887e31",
         *           "signatureHex": "378100766f39f15700855e4048a82590a4944abdd097d54f3ac89707e28d535bc845e030dad4a429b1b6464b9a8112f479f028c9dae467419a3e53fbc50f98eb"
         *         }
         *       ],
         *       "members": [
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A01",
         *           "outputIndex": 0,
         *           "verdict": "allowed"
         *         },
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A02",
         *           "outputIndex": 1,
         *           "verdict": "allowed"
         *         }
         *       ],
         *       "boundsRemaining": {
         *         "per_tx_cap": {
         *           "limit": "200000000",
         *           "used": "199000000",
         *           "remaining": "1000000"
         *         },
         *         "velocity_burst": {
         *           "limit": "10",
         *           "used": "2",
         *           "remaining": "8",
         *           "windowResetsAt": "2026-09-15T21:05:11Z"
         *         },
         *         "hourly_outflow": {
         *           "limit": "2000000000",
         *           "used": "1131000000",
         *           "remaining": "869000000",
         *           "windowResetsAt": "2026-09-15T22:00:00Z"
         *         },
         *         "daily_outflow": {
         *           "limit": "8000000000",
         *           "used": "3410000000",
         *           "remaining": "4590000000",
         *           "windowResetsAt": "2026-09-16T21:04:11Z"
         *         },
         *         "monthly_outflow": {
         *           "limit": "50000000000",
         *           "used": "3410000000",
         *           "remaining": "46590000000",
         *           "windowResetsAt": "2026-10-15T21:04:11Z"
         *         },
         *         "per_seller_cap": {
         *           "limit": "500000000",
         *           "used": "199000000",
         *           "remaining": "301000000",
         *           "windowResetsAt": "2026-09-16T21:04:11Z",
         *           "scope": "sellerVkeyHash:012fde0a6fa2c5f3233b3cf1a9f4281fc3c766da7feea4310c00718b"
         *         },
         *         "envelope": {
         *           "limit": "200000000000",
         *           "used": "3410000000",
         *           "remaining": "196590000000"
         *         }
         *       },
         *       "journalRef": "https://journal.exchain.network/dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        CosignAllow: components["schemas"]["Envelope"] & {
            decisionId: components["schemas"]["DecisionId"];
            /** @description What the enclave decoded, not what the request claimed. */
            txBodyHash: components["schemas"]["Blake2b256"];
            requiredSigners: components["schemas"]["KeyHash"][];
            quorumMembers: string[];
            /** @description A CBOR `transaction_witness_set` containing only vkey witnesses (key 0). */
            witnessSetHex: string;
            witnesses: components["schemas"]["Witness"][];
            /** @description Same length and order as `intents`; every verdict is `allowed`. */
            members: (components["schemas"]["MemberVerdict"] & {
                /** @enum {string} */
                verdict?: "allowed";
            })[];
            boundsRemaining: components["schemas"]["BoundsRemaining"];
            /** Format: uri */
            journalRef: string;
        };
        Rebuild: {
            /** @description The admitted `purchaseId`s; rebuild with exactly these under the same `batchId`. */
            keep: string[];
            batchId: components["schemas"]["Uuid"];
            heldUntil: components["schemas"]["DateTime"];
        };
        /**
         * @description `denied == member_denied`: `rebuild` is present, at least one member is `denied`, no member is
         *     `not_evaluated` and `alarm` is false. `denied` is a batch-level code: every member is
         *     `not_evaluated`, `reasonEnglish` is present, `rebuild` is absent and `alarm` is true exactly for
         *     `body_mismatch`, `payee_unpinned` and `clock_skew`.
         * @example {
         *       "decisionId": "dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "txBodyHash": "blake2b_256:f13f1c9731cd0d3aae2abf45e553c1fd7c94d48ba42c7515eb218aa23c247f18",
         *       "requiredSigners": [
         *         "903105119401d2618ca8b5193adfc74592a1362c07a375c3490fe90e",
         *         "b02e5e1f6167ef12fe823d259b1034f56818e92ef2b4c73722ee3412",
         *         "32c72c8379803dd1957e426ca9c11ffeb47c8dd1a644028214ef39ef",
         *         "347d7c288cd19c106e46e990bd0d38be27fe73fe7aa04b6cbdb9d4ad"
         *       ],
         *       "denied": "member_denied",
         *       "members": [
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A01",
         *           "outputIndex": 0,
         *           "verdict": "allowed"
         *         },
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A03",
         *           "outputIndex": 1,
         *           "verdict": "denied",
         *           "denied": "hourly_outflow",
         *           "reasonEnglish": "This would take the hour's spending to 2,140 USDCx. The mandate allows 2,000 USDCx. Retry after 22:00 UTC.",
         *           "bound": "2000000000",
         *           "used": "1941000000",
         *           "attempted": "199000000",
         *           "retryAfterSec": 3349,
         *           "windowResetsAt": "2026-09-15T22:00:00Z"
         *         },
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A02",
         *           "outputIndex": 2,
         *           "verdict": "allowed"
         *         }
         *       ],
         *       "rebuild": {
         *         "keep": [
         *           "pur_01J9XK3M4N5P6Q7R8S9T0V1A01",
         *           "pur_01J9XK3M4N5P6Q7R8S9T0V1A02"
         *         ],
         *         "batchId": "7f0c3d2e-9a4b-4c1d-8e2f-3a4b5c6d7e8f",
         *         "heldUntil": "2026-09-15T21:06:11Z"
         *       },
         *       "alarm": false,
         *       "journalRef": "https://journal.exchain.network/dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         * @example {
         *       "decisionId": "dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "txBodyHash": "blake2b_256:f13f1c9731cd0d3aae2abf45e553c1fd7c94d48ba42c7515eb218aa23c247f18",
         *       "requiredSigners": [
         *         "903105119401d2618ca8b5193adfc74592a1362c07a375c3490fe90e",
         *         "b02e5e1f6167ef12fe823d259b1034f56818e92ef2b4c73722ee3412",
         *         "32c72c8379803dd1957e426ca9c11ffeb47c8dd1a644028214ef39ef",
         *         "347d7c288cd19c106e46e990bd0d38be27fe73fe7aa04b6cbdb9d4ad"
         *       ],
         *       "denied": "body_mismatch",
         *       "reasonEnglish": "The transaction body does not match the declared purchases. This is a security event.",
         *       "members": [
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A01",
         *           "outputIndex": 0,
         *           "verdict": "not_evaluated"
         *         },
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A02",
         *           "outputIndex": 1,
         *           "verdict": "not_evaluated"
         *         }
         *       ],
         *       "alarm": true,
         *       "journalRef": "https://journal.exchain.network/dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         * @example {
         *       "decisionId": "dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "txBodyHash": "blake2b_256:f13f1c9731cd0d3aae2abf45e553c1fd7c94d48ba42c7515eb218aa23c247f18",
         *       "requiredSigners": [
         *         "903105119401d2618ca8b5193adfc74592a1362c07a375c3490fe90e",
         *         "b02e5e1f6167ef12fe823d259b1034f56818e92ef2b4c73722ee3412",
         *         "32c72c8379803dd1957e426ca9c11ffeb47c8dd1a644028214ef39ef",
         *         "347d7c288cd19c106e46e990bd0d38be27fe73fe7aa04b6cbdb9d4ad"
         *       ],
         *       "denied": "utxo_unknown",
         *       "reasonEnglish": "The wallet input is not a guarded wallet this service knows.",
         *       "members": [
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A01",
         *           "outputIndex": 0,
         *           "verdict": "not_evaluated"
         *         },
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A02",
         *           "outputIndex": 1,
         *           "verdict": "not_evaluated"
         *         }
         *       ],
         *       "alarm": false,
         *       "journalRef": "https://journal.exchain.network/dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        CosignDeny: components["schemas"]["Envelope"] & {
            decisionId: components["schemas"]["DecisionId"];
            txBodyHash: components["schemas"]["Blake2b256"];
            requiredSigners: components["schemas"]["KeyHash"][];
            /** @enum {string} */
            denied: "member_denied" | "asset_not_listed" | "body_mismatch" | "payee_unpinned" | "utxo_unknown" | "clock_skew" | "reservation_conflict";
            reasonEnglish?: string;
            /** @description A machine detail of a batch-level code, e.g. `stale_ref`. */
            detail?: string;
            /** @description Same length and order as `intents`. */
            members: components["schemas"]["MemberVerdict"][];
            rebuild?: components["schemas"]["Rebuild"];
            /** @description True iff `denied` is an alarm code. */
            alarm: boolean;
            /** Format: uri */
            journalRef: string;
        } & ({
            /** @enum {string} */
            denied: "member_denied";
            /** @enum {boolean} */
            alarm?: false;
            members?: {
                /** @enum {string} */
                verdict?: "allowed" | "denied";
            }[];
        } | {
            /** @enum {string} */
            denied: "asset_not_listed" | "utxo_unknown" | "reservation_conflict";
            /** @enum {boolean} */
            alarm?: false;
            members?: {
                /** @enum {string} */
                verdict?: "not_evaluated";
            }[];
        } | {
            /** @enum {string} */
            denied: "body_mismatch" | "payee_unpinned" | "clock_skew";
            /** @enum {boolean} */
            alarm?: true;
            members?: {
                /** @enum {string} */
                verdict?: "not_evaluated";
            }[];
        });
        /**
         * @example {
         *       "error": "quorum_unavailable",
         *       "reachable": 1,
         *       "threshold": 2,
         *       "retryAfterSec": 5,
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        QuorumUnavailable: components["schemas"]["Envelope"] & {
            /** @enum {string} */
            error: "quorum_unavailable";
            reachable: number;
            threshold: number;
            retryAfterSec: number;
        };
        /**
         * @example {
         *       "error": "already_registered",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        Error: components["schemas"]["Envelope"] & {
            error: string;
        };
        /**
         * @example {
         *       "error": "bad_request",
         *       "detail": "intents[0].amount is not an amount",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        ErrorDetail: components["schemas"]["Envelope"] & {
            /** @description A stable machine string, e.g. `unknown_invariant` for a constitution source whose invariant name has no denial code. */
            error: string;
            detail: string;
        };
        /**
         * @example {
         *       "error": "unauthorized",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        ErrorUnauthorized: components["schemas"]["Envelope"] & {
            /** @enum {string} */
            error: "unauthorized";
        };
        /**
         * @example {
         *       "error": "not_found",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        ErrorNotFound: components["schemas"]["Envelope"] & {
            /** @enum {string} */
            error: "not_found";
        };
        /**
         * @example {
         *       "error": "payload_too_large",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        ErrorPayloadTooLarge: components["schemas"]["Envelope"] & {
            /** @enum {string} */
            error: "payload_too_large";
        };
        /**
         * @example {
         *       "error": "rate_limited",
         *       "retryAfterSec": 5,
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        ErrorRateLimited: components["schemas"]["Envelope"] & {
            /** @enum {string} */
            error: "rate_limited";
            retryAfterSec: number;
        };
        /** @description Amounts in minor units of the governed asset; `burstPerMinute` is a count. */
        TemplateParams: {
            perTxCap: components["schemas"]["Amount"];
            daily: components["schemas"]["Amount"];
            perSeller: components["schemas"]["Amount"];
            perAgent: components["schemas"]["Amount"];
            envelope: components["schemas"]["Amount"];
            burstPerMinute: number;
        };
        /** @description Exactly one of a named template with its parameters, or raw constitution source. */
        ConstitutionChoice: {
            /** @enum {string} */
            template: "sokosumi-coworker" | "enterprise-pilot" | "x402-micro";
            params: components["schemas"]["TemplateParams"];
        } | {
            /** @description Constitution DSL. Every invariant name must map to a denial code, else 400 `unknown_invariant`. */
            source: string;
        };
        WalletRegistration: {
            walletAddress: components["schemas"]["Bech32Address"];
            /** @description `<policyId 56 hex>.<assetName hex>` of the wallet state NFT; with `walletAddress` it is the identity of the wallet. */
            stateToken: string;
            ownerKeyHash: components["schemas"]["KeyHash"];
            agentKeyHashes: components["schemas"]["KeyHash"][];
            /** @description Repetition allowed; it is the weighting. */
            quorumKeyHashes: components["schemas"]["KeyHash"][];
            quorumThreshold: number;
            escrowAddresses: components["schemas"]["Bech32Address"][];
            governedAsset: components["schemas"]["AssetSpec"];
            constitution: components["schemas"]["ConstitutionChoice"];
            /** @enum {string} */
            network: "preprod" | "mainnet";
            orgId: string;
            nodeId: string;
            /** @description Refuse a purchase above the seller's price published in the registry. Defaults to `registryGate`. */
            priceGate?: boolean;
            /** @description Percent above the published price the price gate still allows. Default 0. */
            priceTolerancePct?: number;
            /** @description When non-empty, only these counterparties (`sellerVkeyHash:…`) or agent identifiers may be paid. */
            sellerAllowList?: string[];
            /** @description These counterparties (`sellerVkeyHash:…`) or agent identifiers are never paid. */
            sellerDenyList?: string[];
            /**
             * @description When true, every intent's `agentIdentifier` must resolve to a confirmed Masumi registry
             *     entry or the member is denied `registry_gate`. Set false only for wallets whose
             *     counterparties are not registered agents (ground-truth and demo wallets on preprod).
             * @default true
             */
            registryGate: boolean;
        };
        /**
         * @description A numeric rule from the constitution, or one of the Masumi gates (`registry_gate`,
         *     `price_gate`, `seller_allow_list`, `seller_deny_list`), which have no window and no numeric
         *     bound: `bound` is then `null` and `metric` names the check.
         */
        Rule: {
            name: string;
            /** @description The DSL metric, e.g. `sum(payments.amount)`, or the gate's check. */
            metric: string;
            /** @description Window length in seconds; `null` for a gate. */
            window: number | null;
            scope: string | null;
            bound: components["schemas"]["Amount"] | null;
            /** @enum {string} */
            level: "member" | "batch";
        };
        /**
         * @example {
         *       "walletId": "wal_01J9XK3M4N5P6Q7R8S9T0V1W2Z",
         *       "constitutionId": "394b588411cfdb72c9377adba91bb86fad77b65e6be25bdb2a00558ec853e0f2",
         *       "mandateEnglish": "No single payment above 200 USDCx. No more than 10 payments in any 60 seconds. No more than 8,000 USDCx in any rolling 24 hours. No more than 500 USDCx to any one counterparty in any rolling 24 hours. No more than 4,000 USDCx by any one agent in any rolling 24 hours. Total lifetime envelope: 200,000 USDCx. Only registry-verified agents can be paid. No payment above the seller's published price.",
         *       "mandateRules": [
         *         {
         *           "name": "per_tx_cap",
         *           "metric": "max(payments.amount)",
         *           "window": 60,
         *           "scope": null,
         *           "bound": "200000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "velocity_burst",
         *           "metric": "count(payments)",
         *           "window": 60,
         *           "scope": null,
         *           "bound": "10",
         *           "level": "member"
         *         },
         *         {
         *           "name": "daily_outflow",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": null,
         *           "bound": "8000000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "per_seller_cap",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": "counterparty",
         *           "bound": "500000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "per_agent_cap",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": "agent",
         *           "bound": "4000000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "envelope",
         *           "metric": "sum(payments.amount)",
         *           "window": 315360000,
         *           "scope": null,
         *           "bound": "200000000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "registry_gate",
         *           "metric": "counterparty.registered",
         *           "window": null,
         *           "scope": "counterparty",
         *           "bound": null,
         *           "level": "member"
         *         },
         *         {
         *           "name": "price_gate",
         *           "metric": "payments.amount <= counterparty.published_price",
         *           "window": null,
         *           "scope": "counterparty",
         *           "bound": null,
         *           "level": "member"
         *         }
         *       ],
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         * @example {
         *       "walletId": "wal_01M2T4AQTBH4H3FGD52ZXPA4WN",
         *       "constitutionId": "4757c859201c0a43cd6ce125de48868d81272b824501b198bc08ca3d30020a9a",
         *       "mandateEnglish": "No single payment above 150 tADA. No more than 10 payments in any 60 seconds. No more than 8,000 tADA in any rolling 24 hours. No more than 500 tADA to any one counterparty in any rolling 24 hours. No more than 4,000 tADA by any one agent in any rolling 24 hours. Total lifetime envelope: 200,000 tADA.",
         *       "mandateRules": [
         *         {
         *           "name": "per_tx_cap",
         *           "metric": "max(payments.amount)",
         *           "window": 60,
         *           "scope": null,
         *           "bound": "150000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "velocity_burst",
         *           "metric": "count(payments)",
         *           "window": 60,
         *           "scope": null,
         *           "bound": "10",
         *           "level": "member"
         *         },
         *         {
         *           "name": "daily_outflow",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": null,
         *           "bound": "8000000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "per_seller_cap",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": "counterparty",
         *           "bound": "500000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "per_agent_cap",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": "agent",
         *           "bound": "4000000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "envelope",
         *           "metric": "sum(payments.amount)",
         *           "window": 315360000,
         *           "scope": null,
         *           "bound": "200000000000",
         *           "level": "member"
         *         }
         *       ],
         *       "asOf": "2026-09-18T11:27:20.395Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 100000000,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        WalletRegistered: components["schemas"]["Envelope"] & {
            walletId: components["schemas"]["WalletId"];
            constitutionId: components["schemas"]["Hash32"];
            mandateEnglish: string;
            mandateRules: components["schemas"]["Rule"][];
        };
        /**
         * @example {
         *       "walletId": "wal_01J9XK3M4N5P6Q7R8S9T0V1W2Z",
         *       "constitutionId": "394b588411cfdb72c9377adba91bb86fad77b65e6be25bdb2a00558ec853e0f2",
         *       "mandateEnglish": "No single payment above 200 USDCx. No more than 10 payments in any 60 seconds. No more than 8,000 USDCx in any rolling 24 hours. No more than 500 USDCx to any one counterparty in any rolling 24 hours. No more than 4,000 USDCx by any one agent in any rolling 24 hours. Total lifetime envelope: 200,000 USDCx. Only registry-verified agents can be paid. No payment above the seller's published price.",
         *       "mandateRules": [
         *         {
         *           "name": "per_tx_cap",
         *           "metric": "max(payments.amount)",
         *           "window": 60,
         *           "scope": null,
         *           "bound": "200000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "velocity_burst",
         *           "metric": "count(payments)",
         *           "window": 60,
         *           "scope": null,
         *           "bound": "10",
         *           "level": "member"
         *         },
         *         {
         *           "name": "daily_outflow",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": null,
         *           "bound": "8000000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "per_seller_cap",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": "counterparty",
         *           "bound": "500000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "per_agent_cap",
         *           "metric": "sum(payments.amount)",
         *           "window": 86400,
         *           "scope": "agent",
         *           "bound": "4000000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "envelope",
         *           "metric": "sum(payments.amount)",
         *           "window": 315360000,
         *           "scope": null,
         *           "bound": "200000000000",
         *           "level": "member"
         *         },
         *         {
         *           "name": "registry_gate",
         *           "metric": "counterparty.registered",
         *           "window": null,
         *           "scope": "counterparty",
         *           "bound": null,
         *           "level": "member"
         *         },
         *         {
         *           "name": "price_gate",
         *           "metric": "payments.amount <= counterparty.published_price",
         *           "window": null,
         *           "scope": "counterparty",
         *           "bound": null,
         *           "level": "member"
         *         }
         *       ],
         *       "signedBy": {
         *         "ownerKeyHash": "241c5e9eed0f49da2cddd68cfcf3e7dad9201cf8def2c06e4c9f5dac"
         *       },
         *       "writtenAt": "2026-09-14T09:30:00Z",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        Mandate: components["schemas"]["Envelope"] & {
            walletId: components["schemas"]["WalletId"];
            constitutionId: components["schemas"]["Hash32"];
            mandateEnglish: string;
            mandateRules: components["schemas"]["Rule"][];
            signedBy: {
                ownerKeyHash: components["schemas"]["KeyHash"];
            };
            writtenAt: components["schemas"]["DateTime"];
            /** @description The wallet's asset with the symbol the plain-English sentences use. */
            governedAsset?: {
                id: components["schemas"]["AssetId"];
                /** @enum {integer} */
                decimals: 6;
                symbol: string;
            };
        };
        ChainAllowance: {
            periodLimit: components["schemas"]["Amount"];
            spentInPeriod: components["schemas"]["Amount"];
            periodStart: components["schemas"]["DateTime"];
            /** @description Seconds. */
            periodLength: number;
            asOfSlot: number;
        } | null;
        /**
         * @example {
         *       "walletId": "wal_01J9XK3M4N5P6Q7R8S9T0V1W2Z",
         *       "engine": {
         *         "per_tx_cap": {
         *           "limit": "200000000",
         *           "used": "199000000",
         *           "remaining": "1000000"
         *         },
         *         "velocity_burst": {
         *           "limit": "10",
         *           "used": "2",
         *           "remaining": "8",
         *           "windowResetsAt": "2026-09-15T21:05:11Z"
         *         },
         *         "hourly_outflow": {
         *           "limit": "2000000000",
         *           "used": "1131000000",
         *           "remaining": "869000000",
         *           "windowResetsAt": "2026-09-15T22:00:00Z"
         *         },
         *         "daily_outflow": {
         *           "limit": "8000000000",
         *           "used": "3410000000",
         *           "remaining": "4590000000",
         *           "windowResetsAt": "2026-09-16T21:04:11Z"
         *         },
         *         "monthly_outflow": {
         *           "limit": "50000000000",
         *           "used": "3410000000",
         *           "remaining": "46590000000",
         *           "windowResetsAt": "2026-10-15T21:04:11Z"
         *         },
         *         "per_seller_cap": {
         *           "limit": "500000000",
         *           "used": "199000000",
         *           "remaining": "301000000",
         *           "windowResetsAt": "2026-09-16T21:04:11Z",
         *           "scope": "sellerVkeyHash:012fde0a6fa2c5f3233b3cf1a9f4281fc3c766da7feea4310c00718b"
         *         },
         *         "envelope": {
         *           "limit": "200000000000",
         *           "used": "3410000000",
         *           "remaining": "196590000000"
         *         }
         *       },
         *       "chain": {
         *         "periodLimit": "8000000000",
         *         "spentInPeriod": "3410000000",
         *         "periodStart": "2026-09-15T00:00:00Z",
         *         "periodLength": 86400,
         *         "asOfSlot": 71234567
         *       },
         *       "discrepancy": false,
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        Allowance: components["schemas"]["Envelope"] & {
            walletId: components["schemas"]["WalletId"];
            engine: components["schemas"]["BoundsRemaining"];
            chain: components["schemas"]["ChainAllowance"];
            /** @description True when the engine's daily view and the datum's period budget disagree. */
            discrepancy: boolean;
        };
        /**
         * @description Every field except `reasonEnglish` and `windowResetsAt` is bound into the decision's
         *     journal leaf (`proof.leaf`); `bound`, `used` and `attempted` are present iff the denial
         *     code carried them.
         */
        DecisionMember: {
            purchaseId: string;
            outputIndex: number;
            /** @enum {string} */
            verdict: "allowed" | "denied" | "not_evaluated";
            denied?: components["schemas"]["DenialCode"];
            /** @description Present iff `verdict` is `denied`. */
            reasonEnglish?: string;
            bound?: components["schemas"]["Amount"];
            used?: components["schemas"]["Amount"];
            attempted?: components["schemas"]["Amount"];
            windowResetsAt?: components["schemas"]["DateTime"];
            amount: components["schemas"]["Amount"];
            asset: components["schemas"]["AssetId"];
            counterparty: string;
            jobHash: components["schemas"]["Blake2b256"];
            /** @description The agent identifier the request claimed, as the registry gate judged it. */
            agentIdentifier: string;
        };
        DecisionSummary: {
            decisionId: components["schemas"]["DecisionId"];
            at: components["schemas"]["DateTime"];
            /**
             * @description `security` is a denial with an alarm code.
             * @enum {string}
             */
            outcome: "allowed" | "denied" | "security";
            /** @description A machine detail of a batch-level denial, e.g. `stale_ref` when `walletUtxoRef` is not the wallet's current UTxO. */
            detail?: string;
            batchSize: number;
            admitted: number;
            denied: number;
            alarm: boolean;
            txBodyHash: components["schemas"]["Blake2b256"];
            members: components["schemas"]["DecisionMember"][];
        };
        /**
         * @example {
         *       "items": [
         *         {
         *           "decisionId": "dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *           "at": "2026-09-15T21:04:11.412Z",
         *           "outcome": "allowed",
         *           "batchSize": 2,
         *           "admitted": 2,
         *           "denied": 0,
         *           "alarm": false,
         *           "txBodyHash": "blake2b_256:f13f1c9731cd0d3aae2abf45e553c1fd7c94d48ba42c7515eb218aa23c247f18",
         *           "members": [
         *             {
         *               "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A01",
         *               "outputIndex": 0,
         *               "verdict": "allowed",
         *               "amount": "199000000",
         *               "asset": "1c1fa89f7662853c87ca6ac2a8d20fe111930f9be717f87b0a8645a8.5553444378",
         *               "counterparty": "sellerVkeyHash:012fde0a6fa2c5f3233b3cf1a9f4281fc3c766da7feea4310c00718b",
         *               "jobHash": "blake2b_256:091425ca0f10cbdcd679668e6ef65dd50cc23a399ffb133f72f07c42948a6e0c",
         *               "agentIdentifier": "agent-sokosumi-research-01"
         *             },
         *             {
         *               "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A02",
         *               "outputIndex": 1,
         *               "verdict": "allowed",
         *               "amount": "120000000",
         *               "asset": "1c1fa89f7662853c87ca6ac2a8d20fe111930f9be717f87b0a8645a8.5553444378",
         *               "counterparty": "sellerVkeyHash:ef9969491574b01a531d6c7296723a22af5c3da7ec4cbcd74cc9a1a3",
         *               "jobHash": "blake2b_256:db3041f308490e2069c691bec89e89d078f53b03fc4e6e0345d106fdaee76e63",
         *               "agentIdentifier": "agent-sokosumi-writer-07"
         *             }
         *           ]
         *         },
         *         {
         *           "decisionId": "dec_01J9XK3M4N5P6Q7R8S9T0V1W2Y",
         *           "at": "2026-09-15T20:58:02.007Z",
         *           "outcome": "denied",
         *           "batchSize": 1,
         *           "admitted": 0,
         *           "denied": 1,
         *           "alarm": false,
         *           "txBodyHash": "blake2b_256:658b0e927597948e2ee39506424073e3424a3455d0149622d8ed52aca04f18d0",
         *           "members": [
         *             {
         *               "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A03",
         *               "outputIndex": 0,
         *               "verdict": "denied",
         *               "denied": "per_tx_cap",
         *               "bound": "200000000",
         *               "used": "0",
         *               "attempted": "250000000",
         *               "amount": "250000000",
         *               "asset": "1c1fa89f7662853c87ca6ac2a8d20fe111930f9be717f87b0a8645a8.5553444378",
         *               "counterparty": "sellerVkeyHash:c0cae355f89f5e672aa14f659fd13153587c43f31cd358b14115c5b8",
         *               "jobHash": "blake2b_256:7456f31bd43c98a45803b2909ecdb4ba8acf7bea4b6bce958e5c3e7a8b5795e4",
         *               "agentIdentifier": "agent-sokosumi-research-01"
         *             }
         *           ]
         *         }
         *       ],
         *       "nextCursor": null,
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        DecisionPage: components["schemas"]["Envelope"] & {
            items: components["schemas"]["DecisionSummary"][];
            nextCursor: string | null;
        };
        /**
         * @description `leaf` is `blake2b_256("exchain.decision.v1" || decisionId || walletId || request.walletUtxoRef || txBodyHash || outcome || members)`
         *     where each member binds `purchaseId`, `outputIndex`, `amount`, `asset`, `counterparty`, `jobHash`,
         *     `agentIdentifier`, `verdict`, `denied` and, when present, `bound`, `used` and `attempted` (exact byte
         *     layout in the evidence bundle's VERIFY.md), recomputable from this decision alone; `path` is the sibling path, leaf level first, under
         *     `merkle_root` (SHA-256 pairs, last node duplicated on odd levels).
         */
        InclusionProof: {
            leaf: components["schemas"]["Hash32"];
            index: number;
            path: components["schemas"]["Hash32"][];
            root: components["schemas"]["Hash32"];
            rootPublishedAt: components["schemas"]["DateTime"];
            /** @description The wallet's journal epoch the root closes. */
            epoch: number;
        } | null;
        /**
         * @example {
         *       "decisionId": "dec_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "at": "2026-09-15T21:04:11.412Z",
         *       "outcome": "allowed",
         *       "batchSize": 2,
         *       "admitted": 2,
         *       "denied": 0,
         *       "alarm": false,
         *       "txBodyHash": "blake2b_256:f13f1c9731cd0d3aae2abf45e553c1fd7c94d48ba42c7515eb218aa23c247f18",
         *       "members": [
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A01",
         *           "outputIndex": 0,
         *           "verdict": "allowed",
         *           "amount": "199000000",
         *           "asset": "1c1fa89f7662853c87ca6ac2a8d20fe111930f9be717f87b0a8645a8.5553444378",
         *           "counterparty": "sellerVkeyHash:012fde0a6fa2c5f3233b3cf1a9f4281fc3c766da7feea4310c00718b",
         *           "jobHash": "blake2b_256:091425ca0f10cbdcd679668e6ef65dd50cc23a399ffb133f72f07c42948a6e0c",
         *           "agentIdentifier": "agent-sokosumi-research-01"
         *         },
         *         {
         *           "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A02",
         *           "outputIndex": 1,
         *           "verdict": "allowed",
         *           "amount": "120000000",
         *           "asset": "1c1fa89f7662853c87ca6ac2a8d20fe111930f9be717f87b0a8645a8.5553444378",
         *           "counterparty": "sellerVkeyHash:ef9969491574b01a531d6c7296723a22af5c3da7ec4cbcd74cc9a1a3",
         *           "jobHash": "blake2b_256:db3041f308490e2069c691bec89e89d078f53b03fc4e6e0345d106fdaee76e63",
         *           "agentIdentifier": "agent-sokosumi-writer-07"
         *         }
         *       ],
         *       "request": {
         *         "batchId": "7f0c3d2e-9a4b-4c1d-8e2f-3a4b5c6d7e8f",
         *         "walletUtxoRef": "28f7b0d8f8d18672dc472d3b6274a72c592c9d9af2aac88cdae37cacc366dbd3#0",
         *         "intents": [
         *           {
         *             "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A01",
         *             "outputIndex": 0,
         *             "counterparty": "sellerVkeyHash:012fde0a6fa2c5f3233b3cf1a9f4281fc3c766da7feea4310c00718b",
         *             "amount": "199000000",
         *             "asset": "1c1fa89f7662853c87ca6ac2a8d20fe111930f9be717f87b0a8645a8.5553444378",
         *             "jobHash": "blake2b_256:091425ca0f10cbdcd679668e6ef65dd50cc23a399ffb133f72f07c42948a6e0c",
         *             "agentIdentifier": "agent-sokosumi-research-01"
         *           },
         *           {
         *             "purchaseId": "pur_01J9XK3M4N5P6Q7R8S9T0V1A02",
         *             "outputIndex": 1,
         *             "counterparty": "sellerVkeyHash:ef9969491574b01a531d6c7296723a22af5c3da7ec4cbcd74cc9a1a3",
         *             "amount": "120000000",
         *             "asset": "1c1fa89f7662853c87ca6ac2a8d20fe111930f9be717f87b0a8645a8.5553444378",
         *             "jobHash": "blake2b_256:db3041f308490e2069c691bec89e89d078f53b03fc4e6e0345d106fdaee76e63",
         *             "agentIdentifier": "agent-sokosumi-writer-07"
         *           }
         *         ],
         *         "context": {
         *           "nodeId": "masumi-node-eu-1",
         *           "orgId": "org_sokosumi",
         *           "submittedAt": "2026-09-15T21:04:11Z"
         *         }
         *       },
         *       "walletId": "wal_01J9XK3M4N5P6Q7R8S9T0V1W2Z",
         *       "proofPendingUntil": null,
         *       "proof": {
         *         "leaf": "8f714d245f9a3567ba69a58ce07a261181180ef0ce6218c14f191c76aad3303a",
         *         "index": 17,
         *         "path": [
         *           "203f9b6014cc0e6d2e904b384718492c682a5881ff09cdb4274b1a6b39f9f101",
         *           "59745181b1c7dcbb331c0a31c12322a4af20a9caf08b44c568dd653a47e99974",
         *           "789ce0a410ee1e98f99ea5191ef73bec334f13bae19fba72d3a93e6a0d354f1c",
         *           "60809275cb94363d5db117877068f4c34e324b8be46010abcbf89e9c2d9eec8e",
         *           "895ff090f2171f02512536216a480b8d37bd3e3ee4e492659cf175309969e003"
         *         ],
         *         "root": "d0f00b4eb5f17f017601f89a576ae672a90a665216d2749b7ac4e795cb2de471",
         *         "rootPublishedAt": "2026-09-15T22:00:00Z",
         *         "epoch": 1442
         *       },
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        DecisionDetail: components["schemas"]["Envelope"] & components["schemas"]["DecisionSummary"] & {
            /** @description Null for a decision on an unregistered wallet (`utxo_unknown`). */
            walletId: components["schemas"]["WalletId"] | null;
            request: components["schemas"]["CosignRequestBase"];
            proof: components["schemas"]["InclusionProof"];
            /**
             * Format: date-time
             * @description The next root publication that will cover this decision, while `proof` is null.
             */
            proofPendingUntil: string | null;
            /** @description True once a rebuild or a re-evaluation under the same `batchId` replaced this decision. */
            superseded?: boolean;
        };
        QuorumMemberHealth: {
            id: string;
            reachable: boolean;
            attestationAgeSec: number | null;
            pcr0: string | null;
        };
        /**
         * @example {
         *       "backend": "enclave",
         *       "quorum": {
         *         "members": [
         *           {
         *             "id": "exchain-eu-1a",
         *             "reachable": true,
         *             "attestationAgeSec": 412,
         *             "pcr0": "c2c423ee2cbe8ba313dc5416d4603ec811fcc5466aaf39a929637dd435272add35ee6dd9d9305e894aadbb0b2d4aa072"
         *           },
         *           {
         *             "id": "exchain-eu-1b",
         *             "reachable": true,
         *             "attestationAgeSec": 388,
         *             "pcr0": "c2c423ee2cbe8ba313dc5416d4603ec811fcc5466aaf39a929637dd435272add35ee6dd9d9305e894aadbb0b2d4aa072"
         *           },
         *           {
         *             "id": "exchain-eu-1c",
         *             "reachable": false,
         *             "attestationAgeSec": null,
         *             "pcr0": null
         *           }
         *         ],
         *         "threshold": 2,
         *         "reachable": 2
         *       },
         *       "lastCosignAt": "2026-09-15T21:04:11.412Z",
         *       "lastCosignLatencyMs": 187,
         *       "degraded": [
         *         "quorum_member_unreachable:exchain-eu-1c"
         *       ],
         *       "network": "preprod",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        Health: components["schemas"]["Envelope"] & {
            /** @enum {string} */
            backend: "software" | "enclave";
            quorum: {
                members: components["schemas"]["QuorumMemberHealth"][];
                threshold: number;
                reachable: number;
            };
            /** Format: date-time */
            lastCosignAt: string | null;
            lastCosignLatencyMs: number | null;
            /**
             * @description `quorum_member_unreachable:<id>`, `registry` (the Masumi registry read failed closed),
             *     `chain_reader` (the last Blockfrost call failed; `chainTip` is null and the datum step
             *     is skipped) and `watcher` (the watcher has met only errors for `watcher_stale_secs`).
             */
            degraded: string[];
            /** @enum {string} */
            network: "preprod" | "mainnet";
        };
        Anchor: {
            txHash: components["schemas"]["Hash32"];
            slot: number;
        } | null;
        /**
         * @description One wallet's signed root over the decision leaves with WAL sequence numbers `fromSeq..=toSeq`.
         *     `signature` is ed25519 by the publisher key over the canonical JSON (sorted keys, no whitespace)
         *     of `schemaVersion, walletId, epoch, fromSeq, toSeq, count, root, from, to, publishedAt,
         *     publisherKeyHash`. The publisher key is a software key; its `vkey` is served at
         *     `publisher.json` beside the roots.
         */
        JournalRoot: {
            /** @enum {string} */
            schemaVersion?: "1.0";
            walletId: components["schemas"]["WalletId"];
            root: components["schemas"]["Hash32"];
            epoch: number;
            fromSeq: number;
            toSeq: number;
            count: number;
            from: components["schemas"]["DateTime"];
            to: components["schemas"]["DateTime"];
            publishedAt: components["schemas"]["DateTime"];
            publisherKeyHash: components["schemas"]["KeyHash"];
            signature: string;
            anchor: components["schemas"]["Anchor"];
        };
        /**
         * @example {
         *       "items": [
         *         {
         *           "schemaVersion": "1.0",
         *           "walletId": "wal_01J9XK3M4N5P6Q7R8S9T0V1W2Z",
         *           "epoch": 1442,
         *           "fromSeq": 3391,
         *           "toSeq": 3624,
         *           "count": 233,
         *           "root": "d0f00b4eb5f17f017601f89a576ae672a90a665216d2749b7ac4e795cb2de471",
         *           "from": "2026-09-15T21:00:00Z",
         *           "to": "2026-09-15T22:00:00Z",
         *           "publishedAt": "2026-09-15T22:00:00Z",
         *           "publisherKeyHash": "9f5b2c1d0e3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e",
         *           "signature": "15dfa81259a888af570a0ba5a89c120c1718a858771fc11ff0018aaa1ca55dcf4e9d4261a95ad15a9d595ba292f565b53c593524f3b873c41fb503670057a992",
         *           "anchor": {
         *             "txHash": "7d47700f443f864668b04a6f4a02e2017d8796cba2de9dd4034af4e047795fb7",
         *             "slot": 71238100
         *           }
         *         },
         *         {
         *           "schemaVersion": "1.0",
         *           "walletId": "wal_01J9XK3M4N5P6Q7R8S9T0V1W2Z",
         *           "epoch": 1441,
         *           "fromSeq": 3102,
         *           "toSeq": 3390,
         *           "count": 289,
         *           "root": "018c36d16e8ee902a1b920ecdcca39c2f5b90149794a911b7a669d001fd6f1c7",
         *           "from": "2026-09-15T20:00:00Z",
         *           "to": "2026-09-15T21:00:00Z",
         *           "publishedAt": "2026-09-15T21:00:00Z",
         *           "publisherKeyHash": "9f5b2c1d0e3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e",
         *           "signature": "09d5b12341eda4fb617b8803af1c2f19dd5542b3d37a001ffda62ef05b43acb12c0caf26fee8b6c16ddb4c7dd41bf1354f3e3d0f39fa55087dbf59d9b17980b8",
         *           "anchor": null
         *         }
         *       ],
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        RootPage: components["schemas"]["Envelope"] & {
            items: components["schemas"]["JournalRoot"][];
        };
        /**
         * @example {
         *       "token": "rt_01J9XK3M4N5P6Q7R8S9T0V1W2X",
         *       "expiresAt": "2026-09-15T21:19:11Z",
         *       "asOf": "2026-09-15T21:04:11.412Z",
         *       "schemaVersion": "1.1",
         *       "chainTip": {
         *         "slot": 71234567,
         *         "blockHash": "9a301ac2e5747e7ebeeecececd2f114f55695614277514e085211c5417d04c26"
         *       }
         *     }
         */
        ReadToken: components["schemas"]["Envelope"] & {
            /** @description Opaque. */
            token: string;
            expiresAt: components["schemas"]["DateTime"];
        };
    };
    responses: {
        /** @description Malformed input; `detail` says what. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorDetail"];
            };
        };
        /** @description Missing, expired or wrongly scoped bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorUnauthorized"];
            };
        };
        /** @description No such wallet or decision for this token. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorNotFound"];
            };
        };
        /** @description The body exceeds the size limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorPayloadTooLarge"];
            };
        };
        /** @description Too many requests for this token. */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorRateLimited"];
            };
        };
    };
    parameters: {
        /** @description The `batchId`. Must equal the body's `batchId`. */
        IdempotencyKey: string;
        WalletId: components["schemas"]["WalletId"];
        /** @description Inclusive lower bound, RFC 3339. */
        From: string;
        /** @description Exclusive upper bound, RFC 3339. */
        To: string;
    };
    requestBodies: never;
    headers: {
        /** @description Seconds to wait before retrying. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cosign: {
        parameters: {
            query?: never;
            header: {
                /** @description The `batchId`. Must equal the body's `batchId`. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CosignRequest"];
            };
        };
        responses: {
            /** @description Every member admitted; the witness set is attached and the amounts are committed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CosignAllow"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /**
             * @description Denied. `denied` is either `member_denied` (see `members[]` and rebuild with `rebuild.keep`)
             *     or a batch-level code (no member was evaluated). No signature is produced on a denial.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CosignDeny"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
            /**
             * @description Fewer quorum members are reachable than the threshold. Nothing was consumed and nothing was
             *     signed; retry after `Retry-After` seconds with the same `Idempotency-Key`.
             */
            503: {
                headers: {
                    "Retry-After": components["headers"]["RetryAfter"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuorumUnavailable"];
                };
            };
        };
    };
    registerWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletRegistration"];
            };
        };
        responses: {
            /** @description Already registered with an identical body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletRegistered"];
                };
            };
            /** @description Registered; the mandate is compiled and rendered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletRegistered"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The (`walletAddress`, `stateToken`) pair is registered with a different body (`wallet_exists`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    mintReadToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: components["parameters"]["WalletId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token minted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadToken"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getMandate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: components["parameters"]["WalletId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Machine rules and the rendered text, from the same compiled constitution the engine evaluates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mandate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getAllowance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: components["parameters"]["WalletId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The engine's view and the datum's view. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Allowance"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listDecisions: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound, RFC 3339. */
                from?: components["parameters"]["From"];
                /** @description Exclusive upper bound, RFC 3339. */
                to?: components["parameters"]["To"];
                outcome?: "allowed" | "denied" | "security";
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                walletId: components["parameters"]["WalletId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decisionId: components["schemas"]["DecisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decision. `proof` is null until the journal root covering it is published. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: components["parameters"]["WalletId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health of the signing path for this wallet. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listRoots: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound, RFC 3339. */
                from?: components["parameters"]["From"];
                /** @description Exclusive upper bound, RFC 3339. */
                to?: components["parameters"]["To"];
                walletId?: components["schemas"]["WalletId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    getEvidence: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound, RFC 3339. */
                from?: components["parameters"]["From"];
                /** @description Exclusive upper bound, RFC 3339. */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path: {
                walletId: components["parameters"]["WalletId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A zip archive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["PayloadTooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": "ok";
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The quorum is reachable at threshold and the journal is writable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": "ok";
                };
            };
            /** @description Not ready; the body names what is missing. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
