/**
 * Open a Hydra head.
 *
 * A head is opened by proposing it over a *relation* — the long-lived channel
 * between our wallet and one counterparty's. Everything else follows from that:
 * the service picks a connected node, provisions a hydra-node on it, exchanges
 * signed material with the counterparty's payment service, starts the node and
 * records the head.
 *
 * Nothing about the node is configured here, and deliberately so. Its keys are
 * generated by its Host and never leave it, and the counterparty's identity
 * comes from material they signed rather than from a URL typed into this form —
 * which is what stops a stranger opening a head with us.
 */

import { useEffect, useMemo, useState } from 'react';
import { Loader2 } from 'lucide-react';
import { toast } from 'react-toastify';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useAppContext } from '@/lib/contexts/AppContext';
import { useWallets } from '@/lib/queries/useWallets';
import { shortenAddress } from '@/lib/utils';
import { useHydraHosts } from '@/lib/hooks/useHydraHosts';
import {
  createHydraRelation,
  proposeHydraHead,
  recordHydraCounterpartyWallet,
  useHydraRelations,
  useHydraWalletBases,
  type HydraRelation,
} from '@/lib/hooks/useHydraHeads';

type Network = 'Preprod' | 'Mainnet';

type AddHydraHeadDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreated: () => void;
};

function isCardanoNetwork(value: string | undefined): value is Network {
  return value === 'Preprod' || value === 'Mainnet';
}

function walletLabel(wallet?: {
  note?: string | null;
  walletAddress?: string;
  type?: string;
}): string {
  if (!wallet) return 'Unknown wallet';
  const name = wallet.note?.trim() || wallet.type || 'Wallet';
  return wallet.walletAddress ? `${name} · ${shortenAddress(wallet.walletAddress, 8)}` : name;
}

function relationLabel(relation: HydraRelation): string {
  const heads = relation._count?.Heads ?? 0;
  return `${walletLabel(relation.LocalHotWallet)} → ${walletLabel(relation.RemoteWallet)} · ${heads} head${heads === 1 ? '' : 's'}`;
}

export function AddHydraHeadDialog({ open, onOpenChange, onCreated }: AddHydraHeadDialogProps) {
  const { apiClient, selectedPaymentSource } = useAppContext();
  const network = isCardanoNetwork(selectedPaymentSource?.network)
    ? selectedPaymentSource.network
    : undefined;

  const { relations, refetch: refetchRelations } = useHydraRelations(network);
  const { hosts } = useHydraHosts(network);
  const { wallets: localWallets } = useWallets();
  const { wallets: remoteWallets } = useHydraWalletBases(network);

  const [mode, setMode] = useState<'existing' | 'new'>('existing');
  const [relationId, setRelationId] = useState('');
  const [localHotWalletId, setLocalHotWalletId] = useState('');
  const [remoteWalletId, setRemoteWalletId] = useState('');
  const [counterpartyAddress, setCounterpartyAddress] = useState('');
  const [counterpartyBaseUrl, setCounterpartyBaseUrl] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // A head can only be provisioned on a node we hold an admin key for.
  const usableHosts = useMemo(
    () => hosts.filter((host) => host.status === 'Active' && host.hasAdminToken),
    [hosts],
  );
  // A relation with no counterparty URL has nowhere to deliver the offer.
  const proposableRelations = useMemo(
    () => relations.filter((relation) => relation.counterpartyBaseUrl),
    [relations],
  );

  useEffect(() => {
    if (!open) return;
    setMode(proposableRelations.length > 0 ? 'existing' : 'new');
    setRelationId(proposableRelations[0]?.id ?? '');
    setLocalHotWalletId('');
    setRemoteWalletId('');
    setCounterpartyAddress('');
    setCounterpartyBaseUrl('');
  }, [open, proposableRelations]);

  async function handleSubmit() {
    setIsSubmitting(true);
    try {
      let targetRelationId = relationId;

      if (mode === 'new') {
        if (!network) {
          toast.error('Select a Cardano payment source first.');
          return;
        }
        if (!localHotWalletId) {
          toast.error('Choose which of our wallets funds this relation.');
          return;
        }
        if (!remoteWalletId && counterpartyAddress.trim().length === 0) {
          toast.error("Enter the counterparty's wallet address, or pick a recorded one.");
          return;
        }
        if (counterpartyBaseUrl.trim().length === 0) {
          toast.error("The counterparty's payment service URL is required to deliver the offer.");
          return;
        }

        // A pasted address wins: it is the counterparty you just named, and
        // recording it is idempotent, so re-entering the same one is harmless.
        const paymentSourceId = selectedPaymentSource?.id;
        let targetRemoteWalletId = remoteWalletId;
        if (counterpartyAddress.trim().length > 0) {
          if (!paymentSourceId) {
            toast.error('Select a payment source first.');
            return;
          }
          const recorded = await recordHydraCounterpartyWallet(apiClient, {
            paymentSourceId,
            walletAddress: counterpartyAddress.trim(),
            note: 'counterparty',
          });
          targetRemoteWalletId = recorded.id;
        }

        const relation = await createHydraRelation(apiClient, {
          network,
          localHotWalletId,
          remoteWalletId: targetRemoteWalletId,
          counterpartyBaseUrl: counterpartyBaseUrl.trim(),
        });
        targetRelationId = relation.id;
        await refetchRelations();
      }

      if (!targetRelationId) {
        toast.error('Choose a relation to open the head on.');
        return;
      }

      const offer = await proposeHydraHead(apiClient, { hydraRelationId: targetRelationId });
      toast.success(
        `Head offer sent (${offer.status.toLowerCase()}). The head appears once the counterparty accepts and both nodes start.`,
      );
      onCreated();
      onOpenChange(false);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to open the head');
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Open a Hydra head</DialogTitle>
          <DialogDescription>
            Proposes a head to the counterparty. The service provisions the node, exchanges signed
            keys and starts it — nothing here is configured by hand.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {usableHosts.length === 0 && (
            <p className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-300">
              No connected node has an admin key, so no head can be provisioned. Connect one first.
            </p>
          )}

          <div className="space-y-2">
            <Label htmlFor="hydra-head-mode">Relation</Label>
            <Select value={mode} onValueChange={(value) => setMode(value as 'existing' | 'new')}>
              <SelectTrigger id="hydra-head-mode">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="existing" disabled={proposableRelations.length === 0}>
                  Use an existing relation
                </SelectItem>
                <SelectItem value="new">Create a new relation</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {mode === 'existing' ? (
            <div className="space-y-2">
              <Label htmlFor="hydra-head-relation">Open on</Label>
              <Select value={relationId} onValueChange={setRelationId}>
                <SelectTrigger id="hydra-head-relation">
                  <SelectValue placeholder="Choose a relation" />
                </SelectTrigger>
                <SelectContent>
                  {proposableRelations.map((relation) => (
                    <SelectItem key={relation.id} value={relation.id}>
                      {relationLabel(relation)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <p className="text-xs text-muted-foreground">
                Heads are sequential within a relation; this opens the next one.
              </p>
            </div>
          ) : (
            <>
              <div className="space-y-2">
                <Label htmlFor="hydra-head-local">Our wallet</Label>
                <Select value={localHotWalletId} onValueChange={setLocalHotWalletId}>
                  <SelectTrigger id="hydra-head-local">
                    <SelectValue placeholder="Choose a hot wallet" />
                  </SelectTrigger>
                  <SelectContent>
                    {localWallets.map((wallet) => (
                      <SelectItem key={wallet.id} value={wallet.id}>
                        {walletLabel(wallet)}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="hydra-head-counterparty-address">Counterparty wallet address</Label>
                <Input
                  id="hydra-head-counterparty-address"
                  value={counterpartyAddress}
                  onChange={(event) => setCounterpartyAddress(event.target.value)}
                  placeholder="addr_test1…"
                  autoComplete="off"
                  spellCheck={false}
                />
                <p className="text-xs text-muted-foreground">
                  Their wallet, as they sent it to you. Offers are only accepted when signed by this
                  wallet, which is what stops a stranger opening a head with us.
                </p>

                {remoteWallets.length > 0 && (
                  <div className="pt-1">
                    <Label htmlFor="hydra-head-remote" className="text-xs text-muted-foreground">
                      …or pick one already recorded
                    </Label>
                    <Select value={remoteWalletId} onValueChange={setRemoteWalletId}>
                      <SelectTrigger id="hydra-head-remote" className="mt-1">
                        <SelectValue placeholder="Recorded counterparties" />
                      </SelectTrigger>
                      <SelectContent>
                        {remoteWallets.map((wallet) => (
                          <SelectItem key={wallet.id} value={wallet.id}>
                            {walletLabel(wallet)}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="hydra-head-counterparty-url">Counterparty service URL</Label>
                <Input
                  id="hydra-head-counterparty-url"
                  value={counterpartyBaseUrl}
                  onChange={(event) => setCounterpartyBaseUrl(event.target.value)}
                  placeholder="https://payments.counterparty.example"
                  autoComplete="off"
                />
                <p className="text-xs text-muted-foreground">
                  Their payment service, where head offers are delivered.
                </p>
              </div>
            </>
          )}
        </div>

        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button
            type="button"
            onClick={() => void handleSubmit()}
            disabled={isSubmitting || usableHosts.length === 0}
          >
            {isSubmitting && <Loader2 className="h-4 w-4 animate-spin" />}
            Propose head
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
