/**
 * Which hosts may reach which peer port.
 *
 * The peer plane is the one Hydra surface that cannot authenticate its callers:
 * it carries etcd raft, so there is no token to present and no handshake to
 * gate. ADR 0010 §1 therefore protects it with a per-head IP allow-list, which
 * costs nothing because a counterparty's address must already be known to set
 * `--peer`.
 *
 * This module derives that allow-list from what the Host already knows. It is
 * pure: it emits the rules rather than applying them, because the container
 * cannot alter the host firewall it is running behind and should not try. The
 * operator (or the platform) applies them.
 *
 * Peer hosts are emitted as configured, not resolved. ADR 0010 chose hostnames
 * precisely so a counterparty's IP change is absorbed by DNS rather than
 * forcing a restart; baking a resolved address into a firewall rule would throw
 * that away. Callers that need literal addresses resolve at apply time and
 * re-apply on change.
 */

import type { NodeRecord } from '../registry/types.js';

export type PeerAllowRule = {
	nodeId: string;
	/** The port this node listens on for raft traffic. */
	peerPort: number;
	/** Hosts permitted to reach it, taken from each peer's advertise address. */
	allowedHosts: string[];
	/**
	 * True when the node has no peers yet, which means the port must stay shut.
	 * A provisioned-but-unpeered node is the window in which an open peer port
	 * protects nothing at all.
	 */
	closed: boolean;
};

export type PeerAllowlist = {
	rules: PeerAllowRule[];
	/** Ports in the configured peer range with no node on them. */
	unusedPorts: number[];
};

/** Strip the `:port` from an advertise address, leaving the host. */
export function hostOfAdvertise(advertise: string): string {
	const colon = advertise.lastIndexOf(':');
	return colon === -1 ? advertise : advertise.slice(0, colon);
}

export function buildPeerAllowlist(records: NodeRecord[], peerRange: { start: number; count: number }): PeerAllowlist {
	const rules = records
		.map((record) => {
			const allowedHosts = [...new Set(record.peers.map((peer) => hostOfAdvertise(peer.advertise)))].sort();
			return {
				nodeId: record.nodeId,
				peerPort: record.peerPort,
				allowedHosts,
				closed: allowedHosts.length === 0,
			};
		})
		.sort((a, b) => a.peerPort - b.peerPort);

	const used = new Set(rules.map((rule) => rule.peerPort));
	const unusedPorts: number[] = [];
	for (let port = peerRange.start; port < peerRange.start + peerRange.count; port += 1) {
		if (!used.has(port)) {
			unusedPorts.push(port);
		}
	}

	return { rules, unusedPorts };
}

/**
 * Render the allow-list as an nftables ruleset.
 *
 * Default-deny over the whole peer range rather than per-rule accepts alone:
 * a node removed between two applications of this ruleset would otherwise
 * leave its port quietly open.
 */
export function renderNftables(allowlist: PeerAllowlist, peerRange: { start: number; count: number }): string {
	const last = peerRange.start + peerRange.count - 1;
	const lines = [
		'#!/usr/sbin/nft -f',
		'# Generated by hydra-host. Peer plane only; do not hand-edit.',
		'#',
		'# Peer hosts are written as configured. Resolve them at apply time and',
		'# re-apply when DNS changes, or the counterparty loses its route.',
		'',
		'table inet hydra_peer {',
		'\tchain input {',
		'\t\ttype filter hook input priority filter; policy accept;',
		'',
	];

	for (const rule of allowlist.rules) {
		if (rule.closed) {
			lines.push(`\t\t# ${rule.nodeId}: no peers yet, port stays shut`);
			continue;
		}
		const hosts = rule.allowedHosts.join(', ');
		lines.push(`\t\t# ${rule.nodeId}`);
		lines.push(`\t\ttcp dport ${rule.peerPort} ip saddr { ${hosts} } accept`);
	}

	lines.push(
		'',
		'\t\t# Everything else in the peer range, including ports whose node was',
		'\t\t# removed, is refused.',
		`\t\ttcp dport ${peerRange.start}-${last} drop`,
		'\t}',
		'}',
		'',
	);

	return lines.join('\n');
}
