/**
 * Open a real Head on preprod, then close it down again.
 *
 * Opt-in (`HYDRA_E2E_INIT=1`) because it spends testnet funds and waits on
 * chain confirmations. Everything before this phase is free and repeatable;
 * this is the one that proves the whole stack against the actual chain.
 *
 * Each node's Cardano key is generated by its Host and has no funds, so the
 * phase funds both from the wallet the L2 harness already holds, then sends
 * `Init` over the node's own API — through the Host proxy, with the user token,
 * exactly as the payment service would. It tears the head down afterwards, so
 * a run leaves nothing open on chain.
 */

import fs from 'node:fs';
import path from 'node:path';
import { check, phase, skip } from '../check.mjs';
import { BLOCKFROST_PROJECT_FILE } from '../env.mjs';
import { addressFromEnvelope, ada, balanceOf } from '../cardano.mjs';
import {
	headStatus,
	sendCommand,
	teardownHead,
	waitForHeadStatus,
	type NodeEndpoint,
	type Observed,
} from '../head-ws.mjs';
import { http, sleep } from '../procs.mjs';
import type { NodeHandle } from './provision.mjs';

/**
 * Enough for the Init transaction and its fee, and small enough that a run
 * which strands it is not expensive. Init locks a UTxO at the head's script
 * address until the head is closed or aborted.
 */
const FUNDING_LOVELACE = 15_000_000n;
const CONFIRMATION_TIMEOUT_MS = 300_000;
/** How many times to re-send Init while the node's chain follower catches up. */
const INIT_ATTEMPTS = 6;
const INIT_RETRY_DELAY_MS = 60_000;

function projectId(): string {
	return fs.readFileSync(BLOCKFROST_PROJECT_FILE, 'utf8').trim();
}

function endpoint(node: NodeHandle): NodeEndpoint {
	return {
		baseUrl: node.host.spec.baseUrl,
		nodeId: node.nodeId,
		token: node.host.spec.userToken,
		label: node.host.spec.name,
	};
}

/**
 * The Host holds each node's Cardano signing key; the record exposes only the
 * public half, and as the envelope's `cborHex` rather than a whole envelope.
 */
async function nodeAddress(node: NodeHandle): Promise<string> {
	const result = await http(`${node.host.spec.baseUrl}/v1/nodes/${node.nodeId}`, {
		token: node.host.spec.adminToken,
	});
	const body = (result.body ?? {}) as { cardanoVerificationKey?: string };
	if (typeof body.cardanoVerificationKey !== 'string' || body.cardanoVerificationKey.length === 0) {
		throw new Error(`node ${node.nodeId} exposed no cardano verification key`);
	}
	return addressFromEnvelope({ type: 'PaymentVerificationKeyShelley_ed25519', cborHex: body.cardanoVerificationKey });
}

/**
 * Pay each address from the harness wallet.
 *
 * One transaction with one output per node. The outputs are pure ADA by
 * construction — any native tokens on the source UTxOs land in the change —
 * which matters because hydra-node's Init only selects pure-ADA inputs, and a
 * token-bundled UTxO makes Init fail in a way that reads as a protocol bug.
 */
async function fund(signingKeyFile: string, targets: Array<{ address: string; lovelace: bigint }>): Promise<string> {
	const { BlockfrostProvider, MeshTxBuilder, MeshWallet } = await import('@meshsdk/core');
	const { rawKeyHex, readEnvelope } = await import('../cardano.mjs');

	const envelope = readEnvelope(signingKeyFile);
	const provider = new BlockfrostProvider(projectId());
	const wallet = new MeshWallet({
		networkId: 0,
		fetcher: provider,
		submitter: provider,
		key: { type: 'cli', payment: rawKeyHex(envelope.cborHex) },
	});
	await wallet.init();

	// A `cli` MeshWallet derives a *base* address (with a stake part) from the
	// payment key, but a cardano-cli key like this one holds its funds at the
	// *enterprise* address of the same key hash. Asking the wallet for its own
	// UTxOs therefore finds nothing; the inputs and the change have to name the
	// enterprise address explicitly. The witness is valid either way, because
	// both addresses share one payment credential.
	const source = await addressFromEnvelope(envelope);
	const utxos = await provider.fetchAddressUTxOs(source);
	if (utxos.length === 0) {
		throw new Error(`no utxos at ${source}; fund it before running this phase`);
	}

	const builder = new MeshTxBuilder({ fetcher: provider, submitter: provider, verbose: false });
	for (const target of targets) {
		builder.txOut(target.address, [{ unit: 'lovelace', quantity: target.lovelace.toString() }]);
	}
	const unsigned = await builder.changeAddress(source).selectUtxosFrom(utxos).complete();
	// Partial signing: the builder resolved inputs the wallet does not consider
	// its own, and a full sign would refuse them.
	const signed = await wallet.signTx(unsigned, true);
	return wallet.submitTx(signed);
}

async function waitForFunds(address: string, atLeast: bigint): Promise<boolean> {
	const deadline = Date.now() + CONFIRMATION_TIMEOUT_MS;
	while (Date.now() < deadline) {
		try {
			const balance = await balanceOf(address, projectId());
			if (balance.lovelace >= atLeast && balance.pureAdaUtxos > 0) {
				return true;
			}
		} catch {
			// Blockfrost hiccup; the deadline is the guard.
		}
		await sleep(10_000);
	}
	return false;
}

function seedInputMissing(observed: Observed): boolean {
	return observed.messages.some(
		(message) => message.tag === 'PostTxOnChainFailed' && JSON.stringify(message).includes('NoSeedInput'),
	);
}

/**
 * Blockfrost confirming the funding transaction is not the same as the node's
 * own chain follower having observed it. Until it has, Init fails with
 * `NoSeedInput` — no UTxO to consume for the head's tokens — and the follower's
 * lag is the documented Blockfrost drift, not a fixed delay. So this retries
 * rather than sleeping once and hoping.
 */
async function initWithRetries(node: NodeEndpoint): Promise<Observed> {
	let observed: Observed = { tags: [], messages: [], error: null };
	for (let attempt = 1; attempt <= INIT_ATTEMPTS; attempt += 1) {
		observed = await sendCommand(node, { tag: 'Init' }, 60_000);
		if (!seedInputMissing(observed)) {
			return observed;
		}
		console.log(`  [2mattempt ${attempt}: the node has not observed its funding UTxO yet (NoSeedInput)[0m`);
		if (attempt < INIT_ATTEMPTS) {
			await sleep(INIT_RETRY_DELAY_MS);
		}
	}
	return observed;
}

/**
 * Never abort the run.
 *
 * This phase talks to a public network and spends funds, so it has failure
 * modes none of the local phases do. Letting one of them throw would discard
 * the hundred passing results that came before it.
 */
export async function checkHeadInit(nodes: NodeHandle[], fundingKeyFile: string): Promise<void> {
	phase('head: init on preprod');
	try {
		await runHeadInit(nodes, fundingKeyFile);
	} catch (error) {
		check('opening a head on preprod', false, (error as Error).message);
	}
}

async function runHeadInit(nodes: NodeHandle[], fundingKeyFile: string): Promise<void> {
	if (process.env.HYDRA_E2E_INIT !== '1') {
		skip('opening a head on preprod', 'set HYDRA_E2E_INIT=1 to run; it spends testnet funds');
		return;
	}
	if (!fs.existsSync(fundingKeyFile)) {
		skip('opening a head on preprod', `no funding key at ${fundingKeyFile}`);
		return;
	}

	// A run that strands funds must say where they went. The signing key stays on
	// disk under the Host's data directory, so the funds are recoverable — but
	// only until the next run wipes it, which `HYDRA_E2E_KEEP=1` prevents.
	const addresses = await Promise.all(nodes.map((node) => nodeAddress(node)));
	nodes.forEach((node, index) => {
		const keyFile = path.join(node.host.spec.dataDir, 'nodes', node.nodeId, 'keys', 'cardano.sk');
		console.log(`  [2m${node.host.spec.name} node ${addresses[index]}[0m`);
		console.log(`  [2m${''.padEnd(node.host.spec.name.length)} key ${keyFile}[0m`);
	});
	console.log(`  [2mfunding ${ada(FUNDING_LOVELACE)} per node[0m`);

	try {
		const txHash = await fund(
			fundingKeyFile,
			addresses.map((address) => ({ address, lovelace: FUNDING_LOVELACE })),
		);
		check('the funding transaction was submitted', txHash.length === 64, txHash);
	} catch (error) {
		check('the funding transaction was submitted', false, (error as Error).message);
		skip('opening a head on preprod', 'the nodes could not be funded');
		return;
	}

	const funded = await Promise.all(addresses.map((address) => waitForFunds(address, FUNDING_LOVELACE)));
	funded.forEach((ok, index) => {
		check(`${nodes[index].host.spec.name} node address is funded on chain`, ok, addresses[index]);
	});
	if (!funded.every(Boolean)) {
		skip('opening a head on preprod', 'the funding transaction did not confirm in time');
		return;
	}

	const ours = endpoint(nodes[0]);
	const theirs = endpoint(nodes[1]);

	const observed = await initWithRetries(ours);
	check(
		'the node accepted the Init command',
		!observed.tags.includes('CommandFailed') && !observed.tags.includes('PostTxOnChainFailed'),
		[...new Set(observed.tags)].join(', '),
	);

	// Submitting the InitTx and *observing* it are different events. The node
	// reports the head only once its own chain follower sees the transaction,
	// which on the Blockfrost backend trails submission by minutes. A head that
	// has already collected both (empty) commits reports `Open` rather than
	// `Initializing`, so either is a success.
	const opened = await waitForHeadStatus(ours, ['Initializing', 'Open']);
	check('the head exists on chain', opened, opened ? await headStatus(ours) : 'never observed');

	// The counterparty must observe the same head; that is the point of the peer
	// plane, and it is what makes the head jointly usable.
	const peerSees = await waitForHeadStatus(theirs, ['Initializing', 'Open']);
	check('the counterparty node sees the head too', peerSees, peerSees ? await headStatus(theirs) : 'never observed');

	if (!opened) {
		return;
	}

	if (process.env.HYDRA_E2E_KEEP_HEAD === '1') {
		skip('closing the head afterwards', 'HYDRA_E2E_KEEP_HEAD=1');
		return;
	}

	// Leaving a head open would strand its min-ADA and the minted state token in
	// a script address, recoverable only from keys the next run deletes.
	const teardown = await teardownHead(ours, (message) => console.log(`  [2m${message}[0m`));
	check('the head was closed down again', teardown.ok, `${teardown.path} -> ${teardown.finalStatus}`);
}
