name = "nmkr/masumi-smart-wallet"
version = "0.0.0"
compiler = "v1.1.23"
plutus = "v3"
license = "Apache-2.0"
description = "Agent spending-policy smart wallet for project 'nmkr/masumi-smart-wallet'"

[repository]
user = "nmkr"
project = "masumi-smart-wallet"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.1.0"
source = "github"

[config]
