name = "nmkr/masumi-registry"
version = "0.0.0"
compiler = "v1.1.7"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'nmkr/masumi-registry'"

[repository]
user = "nmkr"
project = "masumi-registry"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
