name: Deploy to Azure VM (Payment Service)

# Azure VM deployment workflow for Masumi Payment Service
# This workflow deploys the payment service to an Azure VM with Docker and Docker Compose installed

on:
  push:
    branches:
      - feature/docker-compose  # Change this to the branch you want to trigger deployments
  workflow_dispatch:
    inputs:
      branchOrTag:
        description: 'Branch or tag to deploy (e.g., deploy, main)'
        required: true
        default: 'feature/docker-compose'  # Change this default to match your branch

env:
  BLOCKFROST_API_KEY_PREPROD: ${{ secrets.BLOCKFROST_API_KEY_PREPROD }}
  BLOCKFROST_API_KEY_MAINNET: ${{ secrets.BLOCKFROST_API_KEY_MAINNET }}
  PURCHASE_WALLET_PREPROD_MNEMONIC: ${{ secrets.PURCHASE_WALLET_PREPROD_MNEMONIC }}
  SELLING_WALLET_PREPROD_MNEMONIC: ${{ secrets.SELLING_WALLET_PREPROD_MNEMONIC }}
  COLLECTION_WALLET_PREPROD_ADDRESS: ${{ secrets.COLLECTION_WALLET_PREPROD_ADDRESS }}
  PURCHASE_WALLET_MAINNET_MNEMONIC: ${{ secrets.PURCHASE_WALLET_MAINNET_MNEMONIC }}
  SELLING_WALLET_MAINNET_MNEMONIC: ${{ secrets.SELLING_WALLET_MAINNET_MNEMONIC }}
  COLLECTION_WALLET_MAINNET_ADDRESS: ${{ secrets.COLLECTION_WALLET_MAINNET_ADDRESS }}
  SSL_CERT_PATH: ${{ secrets.SSL_CERT_PATH }}
  SSL_KEY_PATH: ${{ secrets.SSL_KEY_PATH }}
  SSL_CERT_CONTENT: ${{ secrets.SSL_CERT_CONTENT }}
  SSL_KEY_CONTENT: ${{ secrets.SSL_KEY_CONTENT }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'push' && github.ref || inputs.branchOrTag }}
    
    - name: Deploy to Azure VM
      env:
        DEPLOY_REF: ${{ github.event_name == 'push' && github.ref_name || inputs.branchOrTag }}
        AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
        AZURE_VM_USER: ${{ secrets.AZURE_VM_USER || 'azureuser' }}
        DEPLOYMENT_PATH: ${{ secrets.DEPLOYMENT_PATH || '~/masumi-payment-service' }}
      run: |
        # Display deployment information
        echo "==============================================="
        echo "Deployment Information:"
        echo "Branch/Tag: ${DEPLOY_REF}"
        echo "Target: ${AZURE_VM_USER}@${AZURE_VM_IP}:${DEPLOYMENT_PATH}"
        echo "==============================================="
        
        echo "Deploying ${DEPLOY_REF} to ${AZURE_VM_IP}..."
        
        # Thorough cleanup before deployment
        ssh -i ~/.ssh/id_rsa ${AZURE_VM_USER}@${AZURE_VM_IP} 'set -e
          echo "Performing complete cleanup of previous deployment..."
          
          # Stop and clean Docker
          cd "'"${DEPLOYMENT_PATH}"'" 2>/dev/null && {
            echo "Stopping Docker containers..."
            docker-compose down --remove-orphans --volumes --rmi all || true
            docker-compose rm -f || true
          } || true
          
          # Remove Docker resources
          echo "Cleaning Docker resources..."
          docker container prune -f
          docker image prune -f
          docker volume prune -f
          
          # Completely remove and recreate deployment directory
          echo "Removing previous deployment directory..."
          rm -rf "'"${DEPLOYMENT_PATH}"'"
          mkdir -p "'"${DEPLOYMENT_PATH}"'"
          
          echo "Environment reset complete."
        ' || {
          echo "Warning: Environment reset had some issues, but continuing deployment"
        }
        
        # Copy repository files to VM (excluding .env files)
        echo "Copying files to VM..."
        scp -i ~/.ssh/id_rsa -r ./* ./.dockerignore ./.gitignore ${AZURE_VM_USER}@${AZURE_VM_IP}:${DEPLOYMENT_PATH}/ || {
          echo "Error: Failed to copy files to VM"
          exit 1
        }
        
        # Set up SSL certificates if provided
        if [ -n "${{ env.SSL_CERT_CONTENT }}" ] && [ -n "${{ env.SSL_KEY_CONTENT }}" ]; then
          echo "Setting up SSL certificates..."
          
          # Use base64 encoding to avoid special character issues
          CERT_B64=$(echo '${{ env.SSL_CERT_CONTENT }}' | base64 -w 0)
          KEY_B64=$(echo '${{ env.SSL_KEY_CONTENT }}' | base64 -w 0)
          
          ssh -i ~/.ssh/id_rsa ${AZURE_VM_USER}@${AZURE_VM_IP} "set -e; \
            mkdir -p ${DEPLOYMENT_PATH}/nginx/certs; \
            echo ${CERT_B64} | base64 -d > ${DEPLOYMENT_PATH}/nginx/certs/server.crt; \
            echo ${KEY_B64} | base64 -d > ${DEPLOYMENT_PATH}/nginx/certs/server.key; \
            chmod 644 ${DEPLOYMENT_PATH}/nginx/certs/server.crt; \
            chmod 600 ${DEPLOYMENT_PATH}/nginx/certs/server.key; \
            echo 'SSL certificates successfully installed.'
          " || {
            echo "Error: Failed to set up SSL certificates"
            exit 1
          }
        fi
        
        # Handle wallet mnemonics and sensitive data
        # Note: If secrets are not provided, run.sh will auto-generate values
        # which will require a backup from the admin interface after deployment
        BLOCKFROST_API_KEY_PREPROD="${BLOCKFROST_API_KEY_PREPROD:-preprodtestkey_youmustchangethis}"
        BLOCKFROST_API_KEY_MAINNET="${BLOCKFROST_API_KEY_MAINNET:-}"
        PURCHASE_WALLET_PREPROD_MNEMONIC="${PURCHASE_WALLET_PREPROD_MNEMONIC:-}"
        SELLING_WALLET_PREPROD_MNEMONIC="${SELLING_WALLET_PREPROD_MNEMONIC:-}"
        COLLECTION_WALLET_PREPROD_ADDRESS="${COLLECTION_WALLET_PREPROD_ADDRESS:-}"
        PURCHASE_WALLET_MAINNET_MNEMONIC="${PURCHASE_WALLET_MAINNET_MNEMONIC:-}"
        SELLING_WALLET_MAINNET_MNEMONIC="${SELLING_WALLET_MAINNET_MNEMONIC:-}"
        COLLECTION_WALLET_MAINNET_ADDRESS="${COLLECTION_WALLET_MAINNET_ADDRESS:-}"

        # Log configuration (with sensitive data masked)
        echo "Configuration Summary:"
        echo "  BLOCKFROST_API_KEY_PREPROD: ${BLOCKFROST_API_KEY_PREPROD:0:5}...[masked]"
        echo "  BLOCKFROST_API_KEY_MAINNET: ${BLOCKFROST_API_KEY_MAINNET:0:5}...[masked]"
        echo "  Using pre-configured wallets: $([ -n "$PURCHASE_WALLET_PREPROD_MNEMONIC" ] && echo "Yes" || echo "No - Will be auto-generated")"
        
        # Single quotes for the whole SSH command with double quotes for variables
        ssh -i ~/.ssh/id_rsa ${AZURE_VM_USER}@${AZURE_VM_IP} 'set -e
          cd "'"${DEPLOYMENT_PATH}"'"
          
          echo "Making scripts executable..."
          # Make required scripts executable
          find . -name "*.sh" -exec chmod +x {} \;
          
          # Ensure main scripts are executable (in case find failed)
          chmod +x run.sh generate-certificates.sh make-executable.sh 2>/dev/null || true
          
          echo "Running initialization script..."
          ./run.sh \
            --preprod-key "'"${BLOCKFROST_API_KEY_PREPROD}"'" \
            --mainnet-key "'"${BLOCKFROST_API_KEY_MAINNET}"'" \
            --purchase-preprod-mnemonic "'"${PURCHASE_WALLET_PREPROD_MNEMONIC}"'" \
            --selling-preprod-mnemonic "'"${SELLING_WALLET_PREPROD_MNEMONIC}"'" \
            --collection-preprod-address "'"${COLLECTION_WALLET_PREPROD_ADDRESS}"'" \
            --purchase-mainnet-mnemonic "'"${PURCHASE_WALLET_MAINNET_MNEMONIC}"'" \
            --selling-mainnet-mnemonic "'"${SELLING_WALLET_MAINNET_MNEMONIC}"'" \
            --collection-mainnet-address "'"${COLLECTION_WALLET_MAINNET_ADDRESS}"'" || {
            echo "ERROR: Initialization script failed"
            exit 1
          }
          
          echo "Building and starting Docker containers..."
          docker-compose build || {
            echo "ERROR: Docker build failed"
            exit 1
          }
          
          docker-compose up -d || {
            echo "ERROR: Docker compose up failed"
            exit 1
          }
          
          echo "Deployment complete."
          
          # Verify service is running
          echo "Verifying service is running..."
          sleep 10
          if docker-compose ps | grep -q "Up"; then
            echo "Service is running successfully."
          else
            echo "WARNING: Service might not be running properly. Check logs with: docker-compose logs"
            exit 0  # Don't fail deployment if service check is unclear
          fi
        ' || {
          echo "Error: Deployment to VM failed"
          exit 1
        }
        
        echo "Deployment to Azure VM successful!"
        echo "The Masumi Payment Service should now be running at https://${AZURE_VM_IP}/"
