name: Test-runner
on:
  pull_request:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install Backend Dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm run prisma:generate

      - name: Run Jest
        run: pnpm run test

      - name: Run Build
        run: pnpm run build

      - name: Run Open API Generator
        run: pnpm run swagger-json

      - name: Run Backend ESLint
        run: pnpm run lint:backend

      - name: Run Backend TypeScript Check
        run: pnpm run typecheck:backend

      - name: Install Frontend Dependencies
        run: cd frontend && pnpm install

      - name: Generate OpenAPI Types
        run: cd frontend && pnpm run openapi-ts-latest

      - name: Run Frontend ESLint
        run: pnpm -C frontend run lint

      - name: Run Frontend TypeScript Check
        run: pnpm run typecheck:frontend

      - name: Run Next Build
        run: cd frontend && pnpm run build
